spring:
  application:
    name: logistics
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: blueandpurple-logistics
      auto-offset-reset: earliest

server:
  port: 8085

blueandpurple:
  config:
    kafka:
      topics:
        orders-invoicing: 'blueandpurple.orders-invoiced'
        orders-sent: 'blueandpurple.orders-sent'