spring:
  application:
    name: clients
  datasource:
    url: jdbc:postgresql://localhost:5555/blueandpurpleclients
    username: postgres
    password: mitosemeiose
    driver-class-name: org.postgresql.Driver

  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8082
