spring:
  application:
    name: invoicing
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: blueandpurple-invoicing
      auto-offset-reset: earliest

blueandpurple:
  config:
    kafka:
      topics:
        orders-paid: 'blueandpurple.orders-paid'
        orders-invoicing: 'blueandpurple.orders-invoiced'

server:
  port: 8084

minio:
  url: 'http://localhost:9000'
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-name: invoicing
